=== BabuskaBarn/xml-examples/CarRental/car-rental.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
This DTD defines a XML vocabulary, which persists data for the
"car rental" example of this course. 
-->
<!ELEMENT car-rental (stadt*, autokategorie*, kunde*)>

<!ELEMENT stadt (vermiet-station)*>
<!ATTLIST stadt
	stadtcode 				ID #REQUIRED
	name 					CDATA #REQUIRED
	einwohner_anzahl 		CDATA #REQUIRED
>

<!--
Since XML doesn't support composite keys, we introduce a
simple, surrogate primary key "id".
The attributes geoeffnet_von and geoeffnet_bis are missing in the
relational model and are introduced to demonstrate time-literals. 
-->
<!ELEMENT vermiet-station EMPTY>
<!ATTLIST vermiet-station
	id 						ID #REQUIRED
	stations_name 			CDATA #REQUIRED
	adresse					CDATA #REQUIRED
	mitarbeiter_anzahl		CDATA #REQUIRED
	geoeffnet_von			CDATA #IMPLIED
	geoeffnet_bis			CDATA #IMPLIED
>

<!ELEMENT autokategorie EMPTY>
<!ATTLIST autokategorie
	kategorie_bezeichnung 	ID #REQUIRED
	grundtarif 				CDATA #REQUIRED
	km_preis 				CDATA #REQUIRED
>

<!ELEMENT kunde (reservierung)*>
<!ATTLIST kunde
	fuehrerschein_nummer 	ID #REQUIRED
	kunde_name 				CDATA #REQUIRED
	anschrift 				CDATA #REQUIRED
>

<!ELEMENT reservierung EMPTY>
<!ATTLIST reservierung
	vermiet-station-id 		IDREF #REQUIRED
    reservierungs_nr  		CDATA #REQUIRED
    anfangsdatum				CDATA #REQUIRED
    enddatum					CDATA #REQUIRED
    kategorie_bezeichnung	IDREF #REQUIRED
>

=== BabuskaBarn/xml-examples/CarRental/car-rental-bregenz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car-rental SYSTEM "car-rental.dtd">
<car-rental>
	<stadt stadtcode="B__" name="Bregenz" einwohner_anzahl="30000">
		<vermiet-station id="vermiet-station-1" stations_name="Leutbühel" adresse="Leutbühel 1" mitarbeiter_anzahl="2"/>
		<vermiet-station
			id="vermiet-station-2"
			stations_name="Vorkloster"
			adresse="Rheinstarße 41"
			mitarbeiter_anzahl="1"
			geoeffnet_von="08:00:00"
			geoeffnet_bis="19:00:00"/>
	</stadt>

	<stadt stadtcode="DO_" name="Dornbirn" einwohner_anzahl="45000"/>
	<stadt stadtcode="HOH" name="Hohenems" einwohner_anzahl="15000"/>
	<stadt stadtcode="FK_" name="Feldkirch" einwohner_anzahl="34000"/>
	<stadt stadtcode="BZ_" name="Bludenz" einwohner_anzahl="14000"/>
	
	<autokategorie
		kategorie_bezeichnung="Classic-Sport"
		grundtarif="200.0"
		km_preis="1.20"
	/>
	
	<!-- For the purpose of demonstrating datetime literals,
	     anfangsdatum is set to a datetime value. -->
	<kunde
		fuehrerschein_nummer = "A-07177792"
		kunde_name="Dr. Gerhard Schwärzler"
		anschrift="Rathausstraße 2, 6900 Bregenz">
		<reservierung
			vermiet-station-id="vermiet-station-2"
			reservierungs_nr="B.253.265"
			anfangsdatum="2017-12-24T12:00:00"
			enddatum="2017-31-12"
			kategorie_bezeichnung="Classic-Sport"
		/>
	</kunde>
</car-rental>
